eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/
services.goal-service.url=http://goal-service:8082
services.habit-service.url=http://habit-service:8083
services.job-service.url=http://job-tracker-service:8084